paths_llama_2:
- - llama2_7b
  - /share/public/hf_models/Llama-2-7b-hf
  - llama2
  - 7
- - llama2_chat_7b
  - /share/home/zhangshuhai/LLM/models--meta-llama--Llama-2-7b-chat-hf/snapshots/f5db02db724555f92da89c216ac04704f23d4590
  - llama2
  - 7
- - llama2_13b
  - /share/public/hf_models/Llama-2-13b-hf
  - llama2
  - 13
- - llama2_chat_13b
  - /share/home/zhangshuhai/LLM/models--meta-llama--Llama-2-13b-chat-hf/snapshots/a2cb7a712bb6e5e736ca7f8cd98167f81a0b5bd8
  - llama2
  - 13
- - llama2_70b
  - /share/home/zhangshuhai/LLM/models--meta-llama--Llama-2-70b-hf/snapshots/3aba440b59558f995867ba6e1f58f21d0336b5bb
  - llama2
  - 70
- - llama2_chat_70b
  - /share/home/zhangshuhai/LLM/models--meta-llama--Llama-2-70b-chat-hf/snapshots/e9149a12809580e8602995856f8098ce973d1080
  - llama2
  - 70
paths_llama_3:
- - llama3_8b
  - /share/home/zhangshuhai/LLM/models--meta-llama--Meta-Llama-3-8B/snapshots/1460c22666392e470910ce3d44ffeb2ab7dbd4df
  - llama3
  - 8
paths_llama_code:
- - llamaCode_7b
  - /share/home/zhangshuhai/LLM/models--meta-llama--CodeLlama-7b-hf/snapshots/b462c3c99b077d341db691ec780a33156f3c1472
  - Codellama
  - 7
- - llamaCode_13b
  - /share/home/zhangshuhai/LLM/models--meta-llama--CodeLlama-13b-hf/snapshots/bed8c603d9ad262851259de64609337fea3b620d
  - Codellama
  - 13
- - llamaCode_34b
  - /share/home/zhangshuhai/LLM/models--meta-llama--CodeLlama-34b-hf/snapshots/d5270a637cc64c394ad5369880f511c6440dd4cd
  - Codellama
  - 34
- - llamaCode_70b
  - /share/home/zhangshuhai/LLM/models--meta-llama--CodeLlama-70b-hf/snapshots/388132564ff6637a3febc199e63aedc967f126ee
  - Codellama
  - 70
paths_llama_code_instruct:
- - llamaCode_instruct_7b
  - /share/home/zhangshuhai/LLM/models--meta-llama--CodeLlama-7b-Instruct-hf/snapshots/4ce0c40b2ea823bd1d8f1f3fd5bc8a7e80d749bc
  - Codellama
  - 7
- - llamaCode_instruct_13b
  - /share/home/zhangshuhai/LLM/models--meta-llama--CodeLlama-13b-Instruct-hf/snapshots/c24689b733f841ab1a6cce35bccb729f3f7b23fd
  - Codellama
  - 13
- - llamaCode_instruct_34b
  - /share/home/zhangshuhai/LLM/models--meta-llama--CodeLlama-34b-Instruct-hf/snapshots/edf62e7a0389eafc71b8fb1da96008817c0c9edb
  - Codellama
  - 34
- - llamaCode_instruct_70b
  - /share/home/zhangshuhai/LLM/models--meta-llama--CodeLlama-70b-Instruct-hf/snapshots/2826050dce6c8271bb9f667083b64e8254bd374f
  - Codellama
  - 70
paths_llama_code_python:
- - llamaCode_python_7b
  - /share/home/zhangshuhai/LLM/models--meta-llama--CodeLlama-7b-Python-hf/snapshots/b97340ccba60c3ccaf91882ffe470a1bbc32e32c
  - Codellama
  - 7
- - llamaCode_python_13b
  - /share/home/zhangshuhai/LLM/models--meta-llama--CodeLlama-13b-Python-hf/snapshots/c5d87c656d73f4be12d6e0886ce10661ad32669b
  - Codellama
  - 13
- - llamaCode_python_34b
  - /share/home/zhangshuhai/LLM/models--meta-llama--CodeLlama-34b-Python-hf/snapshots/2462f4ca0933c022374e2cac879cc6d296b3f3b1
  - Codellama
  - 34
- - llamaCode_python_70b
  - /share/home/zhangshuhai/LLM/models--meta-llama--CodeLlama-70b-Python-hf/snapshots/b916062ff81cbd5d51efe623b1b3f6ee3b07b7e6
  - Codellama
  - 70
paths_qwen:
- - qwen_0.5b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen1.5-0.5B/snapshots/8f445e3628f3500ee69f24e1303c9f10f5342a39
  - qwen
  - 0.5
- - qwen_chat_0.5b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen1.5-0.5B-Chat/snapshots/f82bd3692de0283f4a4b31e06d164dd8467fb52e
  - qwen
  - 0.5
- - qwen_1.8b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen1.5-1.8B/snapshots/7846de7ed421727b318d6605a0bfab659da2c067
  - qwen
  - 1.8
- - qwen_chat_1.8b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen1.5-1.8B-Chat/snapshots/99f64b6aee2077dc9787342a0eb747fb8126b761
  - qwen
  - 1.8
- - qwen_4b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen1.5-4B/snapshots/a66363a0c24e2155c561e4b53c658b1d3965474e
  - qwen
  - 4
- - qwen_chat_4b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen1.5-4B-Chat/snapshots/6c387a3d44376e831b82d82715e08dca04344e3a
  - qwen
  - 4
- - qwen_7b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen1.5-7B/snapshots/831096e3a59a0789a541415da25ef195ceb802fe
  - qwen
  - 7
- - qwen_chat_7b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen1.5-7B-Chat/snapshots/5f4f5e69ac7f1d508f8369e977de208b4803444b
  - qwen
  - 7
- - qwen_14b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen1.5-14B/snapshots/dce4b190d34470818e5bec2a92cb8233aaa02ca2
  - qwen
  - 14
- - qwen_chat_14b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen1.5-14B-Chat/snapshots/9492b22871f43e975435455f5c616c77fe7a50ec
  - qwen
  - 14
- - qwen_32b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen1.5-32B/snapshots/cefef80dc06a65f89d1d71d0adbc56d335ca2490
  - qwen
  - 32
- - qwen_chat_32b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen1.5-32B-Chat/snapshots/0997b012af6ddd5465d40465a8415535b2f06cfc
  - qwen
  - 32
- - qwen_72b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen1.5-72B/snapshots/93bac0d1ae83d50c43b1793e2d74a00dc43a4c36
  - qwen
  - 72
- - qwen_chat_72b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen1.5-72B-Chat/snapshots/d341a6f2cb937e7a830ecbe3ab7b87215bc3a6b0
  - qwen
  - 72
paths_qwen_1:
- - qwen_1_1.8b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen-1_8B/snapshots/fa6e214ccbbc6a55235c26ef406355b6bfdf5eed
  - qwen_1
  - 1.8
- - qwen_1_chat_1.8b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen-1_8B-Chat/snapshots/1d0f68de57b88cfde81f3c3e537f24464d889081
  - qwen_1
  - 1.8
- - qwen_1_7b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen-7B/snapshots/ef3c5c9c57b252f3149c1408daf4d649ec8b6c85
  - qwen_1
  - 7
- - qwen_1_chat_7b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen-7B-Chat/snapshots/93a65d34827a3cc269b727e67004743b723e2f83
  - qwen_1
  - 7
- - qwen_1_14b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen-14B/snapshots/c4051215126d906ac22bb67fe5edb39a921cd831
  - qwen_1
  - 14
- - qwen_1_chat_14b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen-14B-Chat/snapshots/cdaff792392504e679496a9f386acf3c1e4333a5
  - qwen_1
  - 14
- - qwen_1_72b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen-72B/snapshots/6dae9c86d4f42c3be60ffb525f784ee1991605cb
  - qwen_1
  - 72
- - qwen_1_chat_72b
  - /share/home/zhangshuhai/LLM/models--Qwen--Qwen-72B-Chat/snapshots/6eb5569e56644ea662b048e029de9d093e97d4b6
  - qwen_1
  - 72